---
- name: Check for Homebrew
  command: which brew
  register: brew_check
  changed_when: false
  failed_when: false

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_check.rc != 0

- name: Trust nikitabobko/tap
  command: brew trust nikitabobko/tap
  changed_when: false

- name: Tap nikitabobko/tap (Aerospace cask)
  command: brew tap nikitabobko/tap
  changed_when: false

- name: Install Brewfile packages
  command: brew bundle --file={{ brewfile_path }}
  changed_when: false
