# generated by Git for Windows
test -f ~/.profile && . ~/.profile

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(fzf --bash)"

if type brew &>/dev/null
then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
    do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
    source  "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh"
    source  "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-completion.bash"
else
    echo "brew not in path?"
fi

test -f ~/.bashrc && . ~/.bashrc
